import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth/session";
import { db, foods } from "@/lib/db";

// Sample foods with realistic nutritional data (per 100g unless noted)
const SAMPLE_FOODS = [
  // Proteins
  {
    name: "Chicken Breast",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    servingSizeDescription: "3.5 oz",
    calories: 165,
    proteinG: 31,
    fatG: 3.6,
    saturatedFatG: 1,
    carbsG: 0,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 74,
    cholesterolMg: 85,
    potassiumMg: 256,
    ironMg: 1,
    vitaminB6Mg: 0.6,
    vitaminB12Mcg: 0.3,
  },
  {
    name: "Salmon, Atlantic",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    servingSizeDescription: "3.5 oz fillet",
    calories: 208,
    proteinG: 20,
    fatG: 13,
    saturatedFatG: 3,
    monounsaturatedFatG: 4,
    polyunsaturatedFatG: 5,
    carbsG: 0,
    fiberG: 0,
    sodiumMg: 59,
    cholesterolMg: 55,
    potassiumMg: 363,
    vitaminDMcg: 11,
    vitaminB12Mcg: 3.2,
  },
  {
    name: "Eggs, whole",
    category: "Protein",
    servingSize: 50,
    servingUnit: "g",
    servingSizeDescription: "1 large egg",
    calories: 72,
    proteinG: 6.3,
    fatG: 4.8,
    saturatedFatG: 1.6,
    carbsG: 0.4,
    fiberG: 0,
    sugarG: 0.2,
    cholesterolMg: 186,
    sodiumMg: 71,
    vitaminAMcg: 80,
    vitaminDMcg: 1,
    vitaminB12Mcg: 0.5,
    ironMg: 0.9,
  },
  {
    name: "Ground Beef, 90% lean",
    category: "Protein",
    servingSize: 100,
    servingUnit: "g",
    servingSizeDescription: "3.5 oz",
    calories: 176,
    proteinG: 20,
    fatG: 10,
    saturatedFatG: 4,
    carbsG: 0,
    fiberG: 0,
    cholesterolMg: 70,
    sodiumMg: 66,
    ironMg: 2.5,
    zincMg: 5,
    vitaminB12Mcg: 2.5,
  },
  {
    name: "Greek Yogurt, plain, nonfat",
    category: "Dairy",
    servingSize: 170,
    servingUnit: "g",
    servingSizeDescription: "1 container (6 oz)",
    calories: 100,
    proteinG: 17,
    fatG: 0.7,
    carbsG: 6,
    sugarG: 4,
    fiberG: 0,
    calciumMg: 187,
    potassiumMg: 240,
    sodiumMg: 56,
    vitaminB12Mcg: 1.3,
  },
  // Carbs
  {
    name: "Brown Rice, cooked",
    category: "Grains",
    servingSize: 195,
    servingUnit: "g",
    servingSizeDescription: "1 cup cooked",
    calories: 216,
    proteinG: 5,
    fatG: 1.8,
    carbsG: 45,
    fiberG: 3.5,
    sugarG: 0,
    sodiumMg: 10,
    magnesiumMg: 84,
    phosphorusMg: 150,
    manganeseMg: 1.8,
  },
  {
    name: "Oatmeal, cooked",
    category: "Grains",
    servingSize: 234,
    servingUnit: "g",
    servingSizeDescription: "1 cup cooked",
    calories: 158,
    proteinG: 6,
    fatG: 3.2,
    carbsG: 27,
    fiberG: 4,
    sugarG: 1,
    sodiumMg: 115,
    ironMg: 2,
    magnesiumMg: 56,
    phosphorusMg: 180,
  },
  {
    name: "Sweet Potato, baked",
    category: "Vegetables",
    servingSize: 200,
    servingUnit: "g",
    servingSizeDescription: "1 medium",
    calories: 180,
    proteinG: 4,
    fatG: 0.2,
    carbsG: 41,
    fiberG: 6.6,
    sugarG: 13,
    vitaminAMcg: 1920,
    vitaminCMg: 39,
    potassiumMg: 950,
    manganeseMg: 1,
  },
  {
    name: "Quinoa, cooked",
    category: "Grains",
    servingSize: 185,
    servingUnit: "g",
    servingSizeDescription: "1 cup cooked",
    calories: 222,
    proteinG: 8,
    fatG: 3.5,
    carbsG: 39,
    fiberG: 5,
    sugarG: 2,
    ironMg: 2.8,
    magnesiumMg: 118,
    phosphorusMg: 281,
    folateMcg: 78,
  },
  {
    name: "Banana",
    category: "Fruits",
    servingSize: 118,
    servingUnit: "g",
    servingSizeDescription: "1 medium",
    calories: 105,
    proteinG: 1.3,
    fatG: 0.4,
    carbsG: 27,
    fiberG: 3.1,
    sugarG: 14,
    potassiumMg: 422,
    vitaminB6Mg: 0.4,
    vitaminCMg: 10,
    magnesiumMg: 32,
  },
  // Fats
  {
    name: "Avocado",
    category: "Fruits",
    servingSize: 150,
    servingUnit: "g",
    servingSizeDescription: "1 medium",
    calories: 240,
    proteinG: 3,
    fatG: 22,
    saturatedFatG: 3,
    monounsaturatedFatG: 15,
    carbsG: 13,
    fiberG: 10,
    sugarG: 1,
    potassiumMg: 728,
    vitaminKMcg: 31,
    folateMcg: 121,
    vitaminCMg: 15,
  },
  {
    name: "Olive Oil",
    category: "Fats & Oils",
    servingSize: 14,
    servingUnit: "ml",
    servingSizeDescription: "1 tablespoon",
    calories: 119,
    proteinG: 0,
    fatG: 13.5,
    saturatedFatG: 2,
    monounsaturatedFatG: 10,
    polyunsaturatedFatG: 1.5,
    carbsG: 0,
    fiberG: 0,
    vitaminEMg: 1.9,
    vitaminKMcg: 8,
  },
  {
    name: "Almonds",
    category: "Nuts & Seeds",
    servingSize: 28,
    servingUnit: "g",
    servingSizeDescription: "1 oz (about 23 almonds)",
    calories: 164,
    proteinG: 6,
    fatG: 14,
    saturatedFatG: 1.1,
    monounsaturatedFatG: 9,
    carbsG: 6,
    fiberG: 3.5,
    sugarG: 1,
    vitaminEMg: 7.3,
    magnesiumMg: 76,
    calciumMg: 76,
  },
  {
    name: "Peanut Butter",
    category: "Nuts & Seeds",
    servingSize: 32,
    servingUnit: "g",
    servingSizeDescription: "2 tablespoons",
    calories: 188,
    proteinG: 8,
    fatG: 16,
    saturatedFatG: 3,
    carbsG: 6,
    fiberG: 2,
    sugarG: 3,
    sodiumMg: 136,
    magnesiumMg: 50,
    potassiumMg: 208,
    niacinMg: 4,
  },
  // Vegetables
  {
    name: "Broccoli, cooked",
    category: "Vegetables",
    servingSize: 156,
    servingUnit: "g",
    servingSizeDescription: "1 cup chopped",
    calories: 55,
    proteinG: 3.7,
    fatG: 0.6,
    carbsG: 11,
    fiberG: 5.1,
    sugarG: 2,
    vitaminCMg: 101,
    vitaminKMcg: 220,
    vitaminAMcg: 120,
    folateMcg: 168,
    potassiumMg: 457,
  },
  {
    name: "Spinach, raw",
    category: "Vegetables",
    servingSize: 30,
    servingUnit: "g",
    servingSizeDescription: "1 cup",
    calories: 7,
    proteinG: 0.9,
    fatG: 0.1,
    carbsG: 1.1,
    fiberG: 0.7,
    sugarG: 0.1,
    vitaminAMcg: 141,
    vitaminCMg: 8.4,
    vitaminKMcg: 145,
    folateMcg: 58,
    ironMg: 0.8,
  },
  // Common processed foods
  {
    name: "White Bread",
    brand: "Generic",
    category: "Grains",
    servingSize: 30,
    servingUnit: "g",
    servingSizeDescription: "1 slice",
    calories: 79,
    proteinG: 2.7,
    fatG: 1,
    carbsG: 15,
    fiberG: 0.6,
    sugarG: 1.5,
    sodiumMg: 147,
    calciumMg: 38,
    ironMg: 0.9,
  },
  {
    name: "Pasta, cooked",
    category: "Grains",
    servingSize: 140,
    servingUnit: "g",
    servingSizeDescription: "1 cup cooked",
    calories: 220,
    proteinG: 8,
    fatG: 1.3,
    carbsG: 43,
    fiberG: 2.5,
    sugarG: 1,
    sodiumMg: 1,
    ironMg: 1.8,
    thiaminMg: 0.3,
  },
  {
    name: "Milk, 2% fat",
    category: "Dairy",
    servingSize: 244,
    servingUnit: "ml",
    servingSizeDescription: "1 cup",
    calories: 122,
    proteinG: 8,
    fatG: 4.8,
    saturatedFatG: 3,
    carbsG: 12,
    sugarG: 12,
    fiberG: 0,
    calciumMg: 293,
    vitaminDMcg: 2.9,
    vitaminB12Mcg: 1.3,
    potassiumMg: 342,
  },
  {
    name: "Cheddar Cheese",
    category: "Dairy",
    servingSize: 28,
    servingUnit: "g",
    servingSizeDescription: "1 oz",
    calories: 113,
    proteinG: 7,
    fatG: 9,
    saturatedFatG: 5.7,
    carbsG: 0.4,
    fiberG: 0,
    sugarG: 0.1,
    calciumMg: 200,
    sodiumMg: 174,
    vitaminAMcg: 85,
    vitaminB12Mcg: 0.2,
  },
];

// POST - Seed sample foods (only if foods table is empty)
export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check if foods already exist
    const existingFoods = await db.select().from(foods).limit(1);

    if (existingFoods.length > 0) {
      return NextResponse.json({
        message: "Foods already exist in database",
        count: 0,
      });
    }

    // Insert sample foods
    const insertedFoods = await db
      .insert(foods)
      .values(
        SAMPLE_FOODS.map((food) => ({
          source: "sample" as const,
          name: food.name,
          brand: food.brand || null,
          category: food.category,
          servingSize: String(food.servingSize),
          servingUnit: food.servingUnit,
          servingSizeDescription: food.servingSizeDescription,
          calories: String(food.calories),
          proteinG: String(food.proteinG),
          fatG: String(food.fatG),
          saturatedFatG: String(food.saturatedFatG || 0),
          monounsaturatedFatG: String(food.monounsaturatedFatG || 0),
          polyunsaturatedFatG: String(food.polyunsaturatedFatG || 0),
          carbsG: String(food.carbsG),
          fiberG: String(food.fiberG || 0),
          sugarG: String(food.sugarG || 0),
          sodiumMg: String(food.sodiumMg || 0),
          cholesterolMg: String(food.cholesterolMg || 0),
          potassiumMg: String(food.potassiumMg || 0),
          calciumMg: String(food.calciumMg || 0),
          ironMg: String(food.ironMg || 0),
          magnesiumMg: String(food.magnesiumMg || 0),
          phosphorusMg: String(food.phosphorusMg || 0),
          zincMg: String(food.zincMg || 0),
          manganeseMg: String(food.manganeseMg || 0),
          vitaminAMcg: String(food.vitaminAMcg || 0),
          vitaminCMg: String(food.vitaminCMg || 0),
          vitaminDMcg: String(food.vitaminDMcg || 0),
          vitaminEMg: String(food.vitaminEMg || 0),
          vitaminKMcg: String(food.vitaminKMcg || 0),
          thiaminMg: String(food.thiaminMg || 0),
          niacinMg: String(food.niacinMg || 0),
          vitaminB6Mg: String(food.vitaminB6Mg || 0),
          vitaminB12Mcg: String(food.vitaminB12Mcg || 0),
          folateMcg: String(food.folateMcg || 0),
          isVerified: true,
        }))
      )
      .returning();

    return NextResponse.json({
      message: "Sample foods added successfully",
      count: insertedFoods.length,
    });
  } catch (error) {
    console.error("Seed foods error:", error);
    return NextResponse.json(
      { error: "Failed to seed foods" },
      { status: 500 }
    );
  }
}
